# yaml 配置
services:
  # redis507:
  #   image: "redis:5.0.7"
  #   ports:
  #     - "16379:6379"
  # mysql8019:
  #   image: "mysql:8.0.19"
  #   ports:
  #     - "13306:3306"
  #   command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "moker13579"
  #     MYSQL_DATABASE: "scgptEval"
  #     MYSQL_PASSWORD: "moker13579"
  #   volumes:
  #     - ./init.sql:/data/application/init.sql
  scgpt_eval:
    container_name: scgptEval
    build: .
    image: scgpt_eval
    ports:
      - "80:8089"
    volumes:
      - /home/ubuntu/scgpteval-backend/runs/logs:/app/logs